name: Ccache Build

on:
  push:
    paths: .github/workflows/ccached_build.yml
  workflow_dispatch:
    inputs:
      timeout:
        description: "Timeout in minutes"
        required: false
        type: number
        default: 350

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
         submodules: true
      - uses: ./.github/workflows/ccache_build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: ${{ inputs.timeout }}

  build1:
    needs: build0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
         submodules: true
      - uses: ./.github/workflows/ccache_build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: ${{ inputs.timeout }}

  build2:
    needs: build1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
         submodules: true
      - uses: ./.github/workflows/ccache_build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: ${{ inputs.timeout }}
